// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import ()

type List struct {
	IDOfList int64 
	Name     string `json:"name"`
	Userid   int64
}

type Task struct {
	IDOfTask  int64 `json:"id"`
	Text      string `json:"text"`
	Listid    int64 `json:"listId"`
	Completed bool `json:"completed"`
}

type User struct {
	IDOfUser int64
	Username string	`json:"username"`
	Password string 
}
